- name: Check if secrets are passed
  env:
    NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
    NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
  run: |
    echo "Token length: ${#NOTION_TOKEN}"
    echo "DB ID prefix: ${NOTION_DATABASE_ID:0:6}"
